### PR TITLE
8333457: GenShen: Move remembered set into new generational code

### PR DESCRIPTION
**Pull request by earthling-amzn**
Resolved minor conflict where tenuring threshold was passed to age table when printing it to console.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [JDK-8333457](https://bugs.openjdk.org/browse/JDK-8333457): GenShen: Move remembered set into new generational code (**Task** - P4)

### Reviewers
 * [Kelvin Nilsen](https://openjdk.org/census#kdnilsen) (@kdnilsen - Committer)
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah-jdk21u.git pull/58/head:pull/58` \
`$ git checkout pull/58`

Update a local copy of the PR: \
`$ git checkout pull/58` \
`$ git pull https://git.openjdk.org/shenandoah-jdk21u.git pull/58/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 58`

View PR using the GUI difftool: \
`$ git pr show -t 58`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah-jdk21u/pull/58.diff">https://git.openjdk.org/shenandoah-jdk21u/pull/58.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/shenandoah-jdk21u/pull/58#issuecomment-2176548180)

### CODE REVIEW

**Review by kdnilsen — APPROVED** [review]
Thanks for pulling this together.

**Review by ysramakrishna — APPROVED** [review]
🚢 ... Thank you!

**Pull request closed without merging**
