### PR TITLE
8342214: GenShen: Reduce code duplication in shFreeSet with iterator abstraction

### PR DESCRIPTION
**Pull request by earthling-amzn**
These were almost all clean. All pipeline tests have passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issues
 * [JDK-8342214](https://bugs.openjdk.org/browse/JDK-8342214): GenShen: Reduce code duplication in shFreeSet with iterator abstraction (**Task** - P4)
 * [JDK-8342255](https://bugs.openjdk.org/browse/JDK-8342255): GenShen: Remove unnecessary enum initial values (**Task** - P4)
 * [JDK-8342278](https://bugs.openjdk.org/browse/JDK-8342278): GenShen: Move non-generational mode test out of generational test configuration (**Task** - P4)
 * [JDK-8342560](https://bugs.openjdk.org/browse/JDK-8342560): GenShen: Fix confusing method name (**Task** - P4)
 * [JDK-8342564](https://bugs.openjdk.org/browse/JDK-8342564): GenShen: Only reference young/old generation names in generational mode (**Task** - P4)
 * [JDK-8342580](https://bugs.openjdk.org/browse/JDK-8342580): GenShen: TestChurnNotifications fails executing in unintended test-id modes with ShenandoahGCMode=generational (**Sub-task** - P4)
 * [JDK-8342848](https://bugs.openjdk.org/browse/JDK-8342848): Shenandoah: Marking bitmap may not be completely cleared in generational mode (**Bug** - P4)
 * [JDK-8342919](https://bugs.openjdk.org/browse/JDK-8342919): GenShen: Fix whitespace (**Task** - P4)
 * [JDK-8343227](https://bugs.openjdk.org/browse/JDK-8343227): GenShen: Fold resource mark into management of preselected regions (**Task** - P4)
 * [JDK-8344151](https://bugs.openjdk.org/browse/JDK-8344151): GenShen: Improve comments, clean up unnecessary changes (**Task** - P4)
 * [JDK-8344152](https://bugs.openjdk.org/browse/JDK-8344152): GenShen: Initialize RegionData in product builds (**Task** - P4)
 * [JDK-8344260](https://bugs.openjdk.org/browse/JDK-8344260): GenShen: Excess unaffiliated regions reserved for old will not be transferred to young (**Bug** - P4)
 * [JDK-8344264](https://bugs.openjdk.org/browse/JDK-8344264): GenShen: Improve comments and method names (**Task** - P4)
 * [JDK-8344263](https://bugs.openjdk.org/browse/JDK-8344263): GenShen: Reduce extraneous log messages at INFO level (**Task** - P4)
 * [JDK-8344339](https://bugs.openjdk.org/browse/JDK-8344339): GenShen: Avoid using namespaces (**Task** - P4)
 * [JDK-8344320](https://bugs.openjdk.org/browse/JDK-8344320): GenShen: Possible null pointer usage in shGenerationalHeap (**Bug** - P4)
 * [JDK-8344321](https://bugs.openjdk.org/browse/JDK-8344321): GenShen: Fix various sonar scan warnings (**Bug** - P4)
 * [JDK-8344592](https://bugs.openjdk.org/browse/JDK-8344592): GenShen: Remove unnecessary comments and changes (**Task** - P4)
 * [JDK-8344638](https://bugs.openjdk.org/browse/JDK-8344638): GenShen: Verifier should not touch claim token (**Task** - P4)
 * [JDK-8344640](https://bugs.openjdk.org/browse/JDK-8344640): GenShen: Reuse existing card mark barrier function when dropping references (**Task** - P4)
 * [JDK-8344670](https://bugs.openjdk.org/browse/JDK-8344670): GenShen: Use concurrent worker session for concurrent mark phase (**Task** - P4)
 * [JDK-8344779](https://bugs.openjdk.org/browse/JDK-8344779): GenShen: Consolidate shared heap region closures into one header (**Task** - P4)
 * [JDK-8344797](https://bugs.openjdk.org/browse/JDK-8344797): GenShen: Update and rename confusing method (**Task** - P4)
 * [JDK-8344985](https://bugs.openjdk.org/browse/JDK-8344985): GenShen: Refactor arraycopy barrier for generational mode (**Task** - P4)
 * [JDK-8342734](https://bugs.openjdk.org/browse/JDK-8342734): GenShen: Test failure gc/shenandoah/TestReferenceRefersToShenandoah.java#generational (**Task** - P4)

### Reviewers
 * [Y. Srinivas Ramakrishna](https://openjdk.org/census#ysr) (@ysramakrishna - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/shenandoah-jdk21u.git pull/143/head:pull/143` \
`$ git checkout pull/143`

Update a local copy of the PR: \
`$ git checkout pull/143` \
`$ git pull https://git.openjdk.org/shenandoah-jdk21u.git pull/143/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 143`

View PR using the GUI difftool: \
`$ git pr show -t 143`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/shenandoah-jdk21u/pull/143.diff">https://git.openjdk.org/shenandoah-jdk21u/pull/143.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/shenandoah-jdk21u/pull/143#issuecomment-2536867668)
</details>

### CODE REVIEW

**Comment by earthling-amzn** [comment]
/issue add 8342214,8342255,8342278,8342560,8342564,8342580,8342848,8342919,8343227,8344151,8344152,8344260,8344264,8344263,8344339,8344320,8344321,8344592,8344638,8344640,8344670,8344779,8344797,8344985,8342734

**Comment by ysramakrishna** [comment]
I did a cursory check and it looks good. As regards:

> Issue is already resolved. Consider making this a "backport pull request" by setting the PR title to Backport <hash> with the hash of the original commit.

May be check if that works better and quiets the complaints of the robot overlords? I am guessing `\backport` takes only a single parameter, and multiple `\backport`s can't be composed/nested.

Not sure what the right process is that is recommended here. May be @shipilev has a suggestion?

**Review by ysramakrishna — APPROVED** [review]
LGTM based on a cursory glance at the changes, the correctness of the testing, and the clean-ness of the backports.

**Pull request closed without merging**
